name: packetsender
version: 8.6.9
summary: Packet Sender - Free TCP/UDP/SSL/HTTP Utility
icon: src/pslogo128.png
description: |
  Packet Sender - Free utility to for sending / receiving of network
  packets. TCP, UDP, SSL, and HTTP. https://packetsender.com/

# sudo snap install packetsender*.snap --dangerous

grade: stable
base: core24
confinement: strict
environment:
  QT_PLUGIN_PATH: "$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/qt6/plugins"

apps:
  packetsender:
    command: usr/local/bin/packetsender
    desktop: usr/share/applications/packetsender.desktop
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - home
      - removable-media
      - network
      - cups
      
parts:
  packetsender:
    plugin: qmake
    source: src/
    source-branch: master
    qmake-project-file: src/PacketSenderSnap.pro
    build-packages:
      - build-essential
      - qt6-base-dev
      - libxkbcommon-dev
      - qt6-declarative-dev
      - libgl1-mesa-dev
      - libglvnd-dev
      - libssl-dev

    stage-packages:
      - libqt6core6
      - libqt6gui6
      - libqt6widgets6
      - libqt6network6
      - libqt6printsupport6
      - libcurl4
      - qt6-translations-l10n
      - qt6-gtk-platformtheme
      - qt6-qpa-plugins
      - qt6-wayland
      - cups-client
    after: [desktop-qt6]
      
  desktop-qt6:
      source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
      source-subdir: qt
      plugin: make
      make-parameters: ["FLAVOR=qt6"]
      build-packages:
        - build-essential
        - qt6-base-dev
        - libqt6xml6t64
        - libqt6network6t64
        - dpkg-dev
      stage-packages:
        - libxkbcommon0
        - ttf-ubuntu-font-family
        - dmz-cursor-theme
        - light-themes
        - adwaita-icon-theme
        - gnome-themes-standard
        - shared-mime-info
        - libqt6gui6
        - libgdk-pixbuf2.0-0
        - libqt6svg6
        - appmenu-qt6
        - locales-all
        - xdg-user-dirs
        - fcitx-frontend-qt6
