name: packetsender
version: 8.1.2
summary: Packet Sender - Free TCP/UDP/SSL/HTTP Utility
icon: src/pslogo128.png

description: |
  Packet Sender - Free utility to for sending / receiving of network
  packets and HTTP. TCP, UDP, SSL.

grade: stable
confinement: strict
architectures: [amd64]

parts:
  packetsender:
    plugin: qmake
    project-files: ["src/PacketSenderSnap.pro"]
    source: https://github.com/dannagle/PacketSender.git
    source-branch: master
    qmake-parameters: CONFIG+=qtquickcompiler
    build-packages:
      - qt5-default
    stage-packages:
      - libgl1-mesa-glx
      - libgl1-mesa-dev

